spring.application.name=consulting-service
flask.api.url=http://localhost:5000
flask.engagement.url=http://localhost:5001/predict_engagement
server.port=8029

# Configuration pour Feign
User-Service.url=http://localhost:8023  # Ou l'URL de ton microservice User

feign.client.config.default.loggerLevel=FULL

logging.level.com.maghrebia.Consulting.Feign=DEBUG
logging.level.feign=DEBUG
logging.level.okhttp3=DEBUG
logging.level.httpclient.wire=DEBUG
logging.level.org.apache.http=DEBUG


# Config Client properties
spring.cloud.config.import-check.enabled=false
spring.cloud.config.fail-fast=true

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/maghribeya
# Exclure la configuration automatique de DataSource (base de donn\u00E9es relationnelle)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=achoury.mayem@gmail.com
spring.mail.password=yzhc hcxj kcep xvjm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.mail.javamail=DEBUG
