    spring.application.name=Credit-Service
    server.port=8028

    #eureka register
    eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
    eureka.client.register-with-eureka=true



spring.data.mongodb.uri=mongodb://localhost:27017/maghribia






    #Config Client properties
    spring.cloud.config.import-check.enabled=false
    spring.cloud.config.fail-fast=true
